### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by andysaab** [AlexxIT/yandex_smart_home_fix#1]
Спасибо, Алексей!
Всё заработало!

**Comment by cosmaz** [comment]
Спасибо, что ты есть! )

**Comment by Shulyaka** [comment]
Не нужно ли это смержить в dmitry-k/yandex_smart_home, пока в яндексе или aiohttp не починят? Или даже в HA?

**Comment by tuxamat** [comment]
соединился, но список устройств не обновляет(

**Comment by mmegaromm** [comment]
Только сегодня купил станцию мини
8 часов мучался с сертификатами настройкой роутера и т д
Фикс меня спас 
Спасибо.

**Comment by AlexxIT** [comment]
Фикс чинит только авторизацию. Список устройств, это уже в компоненте Дмитрия. Попробуйте фильтрами уменьшить список устройств

**Comment by tuxamat** [comment]
оставил только свет и свичи - один хрен)

**Comment by AlexxIT** [comment]
@tuxamat нужно пробовать по одному объекту.

**Comment by YaLiC** [comment]
Присоединюсь к благодарностям. Фикс не пригодился, т.к. обновление HA исправляет проблему.
Однако пожимаю Вам руку за труды. Спасибо!

**Comment by tuxamat** [comment]
0.118.4 - все тоже самое

**Comment by AlexxIT** [comment]
@tuxamat проблема не в версии ХА, а в каких-то ваших объектах в ХА. Они ломают API.

**Comment by tuxamat** [comment]
руки пока не дошли разобраться... отпишусь

**Comment by tuxamat** [comment]
Починил. Создал новый диалог с нуля и переподключил в Алисе, все ок.

**Comment by VerityNH** [comment]
к сожалению с верисей HA 2020.12 не работает

**Comment by ARNik** [comment]
> к сожалению с верисей HA 2020.12 не работает

В 2020.12 все работает без фикса.

**Comment by VerityNH** [comment]
> > к сожалению с верисей HA 2020.12 не работает
> 
> В 2020.12 все работает без фикса.

аутентификацию проходит, при попытке получить список устройств - выдает ошибку

```
yandex_smart_home:
  filter:
    include_domains:
      - switch
      - light
      - climate
      - cover
      - fan
      - group
      - scene
      - media_player
      - vacuum
      - sensor
      - humidifier
```
